project_id = "kauqfglsnbmshlteegaf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.send-repair-inquiry]
verify_jwt = false

[functions.send-injury-claim]
verify_jwt = false

[functions.send-purchase-application]
verify_jwt = false

[functions.send-payment-receipt]
verify_jwt = false

[functions.create-bhph-payment]
verify_jwt = true

[functions.verify-stripe-payment]
verify_jwt = true

[functions.create-customer-account]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.generate-vehicle-description]
verify_jwt = true

[functions.chat-assistant]
verify_jwt = false

[functions.generate-quote]
verify_jwt = false

[functions.translate-text]
verify_jwt = false
