import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.inventory": "Inventory",
    "nav.carRepairs": "Car Repairs",
    "nav.injuryClaims": "Injury Claims",
    "nav.login": "Login",
    "nav.dashboard": "Dashboard",
    "nav.getStarted": "Get Started",
    "nav.tagline": "Quality Foreign and Domestic Auto's",
    
    // Hero
    "hero.title": "Cars & Claims",
    "hero.subtitle": "Your trusted marketing partner for vehicle sales, financing and non-fault injury and property damage claims",
    "hero.viewInventory": "View Inventory",
    "hero.injuryClaims": "Injury Claims",
    "hero.carRepairs": "Car Repairs",
    "hero.bhph": "Buy Here Pay Here",
    
    // Services
    "services.title": "Our Services",
    "services.subtitle": "Everything you need in one place",
    "services.autoSales": "Auto Sales",
    "services.autoSalesDesc": "Foreign and domestic used vehicles with transparent pricing",
    "services.bhphFinancing": "Buy-here-pay-here financing",
    "services.digitalReceipts": "Digital payment receipts",
    "services.flexiblePayments": "Flexible payment schedules",
    "services.carRepairs": "Car Repairs",
    "services.carRepairsDesc": "Professional auto repair and maintenance services",
    "services.expertMechanics": "Expert mechanics",
    "services.fastTurnaround": "Fast turnaround times",
    "services.qualityParts": "Quality parts & service",
    "services.injuryClaims": "Injury Claims",
    "services.injuryClaimsDesc": "Professional no-fault injury claim assistance",
    "services.expertProcessing": "Expert claim processing",
    "services.docSupport": "Documentation support",
    "services.fastResolution": "Fast claim resolution",
    
    // CTA
    "cta.title": "Ready to get started?",
    "cta.subtitle": "Create an account to manage your payments or browse our inventory",
    "cta.createAccount": "Create Account",
    
    // Footer
    "footer.contactUs": "Contact Us",
    
    // Language Toggle
    "lang.english": "EN",
    "lang.spanish": "ES",

    // Inventory
    "inventory.title": "Vehicle Inventory",
    "inventory.subtitle": "Browse our selection of quality foreign and domestic vehicles from Quality Foreign and Domestic Auto's",
    "inventory.noVehicles": "No vehicles available at the moment. Check back soon!",
    "inventory.photos": "Photos",
    "inventory.call": "Call",
    "inventory.buyNow": "Buy Now",
    "inventory.mi": "mi",
    "inventory.translating": "Translating...",

    // Purchase Application
    "purchase.title": "Purchase Application",
    "purchase.paymentCalculator": "Payment Calculator",
    "purchase.downPayment": "Down Payment ($)",
    "purchase.term": "Term (months)",
    "purchase.estMonthly": "Est. Monthly",
    "purchase.amountFinanced": "Amount Financed",
    "purchase.totalInterest": "Total Interest",
    "purchase.totalPayment": "Total Payment",
    "purchase.disclaimer": "* Estimated payments based on {rate}% APR simple interest. Actual terms may vary.",
    "purchase.yourInfo": "Your Information",
    "purchase.fullName": "Full Name *",
    "purchase.email": "Email *",
    "purchase.phone": "Phone Number *",
    "purchase.address": "Address *",
    "purchase.notes": "Additional Notes (Optional)",
    "purchase.notesPlaceholder": "Any additional information...",
    "purchase.cancel": "Cancel",
    "purchase.submitting": "Submitting...",
    "purchase.submit": "Submit Application",
    "purchase.successTitle": "Application Submitted!",
    "purchase.successMessage": "Thank you for your interest in the {vehicle}. Our team will review your application and contact you shortly.",
    "purchase.estPayment": "Your Estimated Payment",
    "purchase.perMonth": "/mo",
    "purchase.forMonths": "for {months} months",
    "purchase.continueBrowsing": "Continue Browsing",
    "purchase.goToPortal": "Go to Payment Portal",

    // ChatBot
    "chat.title": "Cars & Claims Assistant",
    "chat.placeholder": "Type a message...",
    "chat.inventory": "Inventory",
    "chat.claims": "Claims",
    "chat.repairs": "Repairs",
    "chat.payments": "Payments",

    // Payment Portal
    "portal.title": "BHPH Payment Portal",
    "portal.subtitle": "Manage your account and make payments",
    "portal.signInDesc": "Sign in to view your account, make payments, and see your payment history.",
    "portal.signIn": "Sign In to Continue",
    "portal.useCalculator": "Or use our payment calculator below",
    "portal.loading": "Loading...",
    "portal.noActiveAccount": "No Active Account",
    "portal.noActiveAccountDesc": "You don't have an active BHPH account. Visit our dealership to get started!",
    "portal.viewInventory": "View Inventory",
    "portal.overview": "Overview",
    "portal.history": "History",
    "portal.calculator": "Calculator",
    "portal.currentBalance": "Current Balance",
    "portal.monthlyPayment": "Monthly Payment",
    "portal.nextPaymentDue": "Next Payment Due",
    "portal.daysOverdue": "{days} days overdue",
    "portal.dueInDays": "Due in {days} days",
    "portal.daysUntilDue": "{days} days until due",
    "portal.vehicle": "Vehicle",
    "portal.originalAmount": "Original Amount",
    "portal.paymentInitiated": "Payment Initiated!",
    "portal.paymentProcessing": "Your payment is being processed. Your account balance will be updated shortly.",
    "portal.dismiss": "Dismiss",
    "portal.paymentHistory": "Payment History",
    "portal.viewPastPayments": "View all your past payments",
    "portal.noPaymentHistory": "No payment history yet",
    "portal.date": "Date",
    "portal.amount": "Amount",
    "portal.principal": "Principal",
    "portal.interest": "Interest",
    "portal.lateFee": "Late Fee",
    "portal.method": "Method",
    "portal.paymentCalculator": "Payment Calculator",
    "portal.calcDesc": "Calculate payments with simple interest",
    "portal.calcDescAlt": "Calculate your monthly payments with simple interest",
    "portal.vehiclePrice": "Vehicle Price ($)",
    "portal.interestRate": "Interest Rate (%)",
    "portal.termMonths": "Term (months)",
    "portal.calculatePayment": "Calculate Payment",
    "portal.totalInterest": "Total Interest",
    "portal.totalPayment": "Total Payment",
    "portal.makePayment": "Make a Payment",
    "portal.chooseMethod": "Choose your preferred payment method",
    "portal.paymentAmount": "Payment Amount",
    "portal.monthly": "Monthly",
    "portal.currentBalanceLabel": "Current balance",
    "portal.creditDebit": "Credit/Debit Card",
    "portal.recommended": "Recommended",
    "portal.payWithCard": "Pay {amount} with Card",
    "portal.processing": "Processing...",
    "portal.cashApp": "Cash App",
    "portal.zelle": "Zelle",
    "portal.includeNameNote": "Include your name in the payment note for faster processing",
    "portal.sendToZelle": "Send to {contact} and include your name in the memo",
    "portal.paymentQuestions": "Questions about payments? Call us at",

    // Repairs
    "repairs.title": "Car Repair Services",
    "repairs.subtitle": "Professional auto repair and maintenance from Quality Foreign and Domestic Auto's",
    "repairs.expertMechanics": "Expert Mechanics",
    "repairs.expertMechanicsDesc": "Certified technicians with years of experience",
    "repairs.expertMechanicsText": "Our skilled mechanics are trained to work on both foreign and domestic vehicles, ensuring quality repairs every time.",
    "repairs.fastService": "Fast Service",
    "repairs.fastServiceDesc": "Quick turnaround times without compromising quality",
    "repairs.fastServiceText": "We understand your time is valuable. Most repairs are completed within 24-48 hours.",
    "repairs.completeService": "Complete Service",
    "repairs.completeServiceDesc": "From oil changes to major repairs",
    "repairs.completeServiceText": "We handle everything from routine maintenance to complex engine repairs and diagnostics.",
    "repairs.qualityParts": "Quality Parts",
    "repairs.qualityPartsDesc": "OEM and high-quality aftermarket parts",
    "repairs.qualityPartsText": "We use only the best parts to ensure your vehicle runs smoothly and safely.",
    "repairs.servicesInclude": "Our Services Include",
    "repairs.servicesIncludeDesc": "Comprehensive automotive repair and maintenance",
    "repairs.engineDiagnostics": "Engine Diagnostics & Repair",
    "repairs.engineDiagnosticsDesc": "Complete engine services and troubleshooting",
    "repairs.brakeServices": "Brake Services",
    "repairs.brakeServicesDesc": "Brake pads, rotors, and complete brake system repair",
    "repairs.transmissionService": "Transmission Service",
    "repairs.transmissionServiceDesc": "Transmission repair and maintenance",
    "repairs.oilChanges": "Oil Changes & Tune-Ups",
    "repairs.oilChangesDesc": "Regular maintenance to keep your car running smoothly",
    "repairs.suspension": "Suspension & Steering",
    "repairs.suspensionDesc": "Alignment, shocks, and steering system repairs",
    "repairs.electrical": "Electrical Systems",
    "repairs.electricalDesc": "Battery, alternator, and electrical diagnostics",
    "repairs.acHeating": "AC & Heating",
    "repairs.acHeatingDesc": "Climate control system repair and maintenance",
    "repairs.tireServices": "Tire Services",
    "repairs.tireServicesDesc": "Tire rotation, balancing, and replacement",
    "repairs.requestQuote": "Request a Repair Quote",
    "repairs.requestQuoteDesc": "Fill out the form below and we'll get back to you shortly",
    "repairs.name": "Name",
    "repairs.phone": "Phone Number",
    "repairs.address": "Address",
    "repairs.year": "Year",
    "repairs.make": "Make",
    "repairs.model": "Model",
    "repairs.issueDescription": "Issue Description",
    "repairs.issueDescriptionPlaceholder": "Please describe the issue you're experiencing with your vehicle...",
    "repairs.photosVideos": "Photos/Videos of Issue (Optional)",
    "repairs.submitting": "Submitting...",
    "repairs.submitInquiry": "Submit Inquiry",
    "repairs.inquirySubmitted": "Inquiry Submitted",
    "repairs.inquirySubmittedDesc": "We've received your repair inquiry and will contact you soon!",
    "repairs.submissionFailed": "Submission Failed",
    "repairs.submissionFailedDesc": "There was an error submitting your inquiry. Please try again.",

    // Claims
    "claims.title": "No-Fault Injury Claims",
    "claims.subtitle": "Professional assistance for your injury claim needs",
    "claims.expertGuidance": "Expert Guidance",
    "claims.expertGuidanceDesc": "Navigate the claims process with professional support",
    "claims.expertGuidanceText": "Our experienced team helps you understand your rights and navigate the no-fault claim process efficiently.",
    "claims.docSupport": "Documentation Support",
    "claims.docSupportDesc": "Help with all required paperwork and documentation",
    "claims.docSupportText": "We assist with gathering and organizing all necessary documentation to support your claim.",
    "claims.fastProcessing": "Fast Processing",
    "claims.fastProcessingDesc": "Quick turnaround on claim submissions",
    "claims.fastProcessingText": "We work efficiently to ensure your claim is processed as quickly as possible.",
    "claims.confidential": "Confidential Service",
    "claims.confidentialDesc": "Your information is protected and secure",
    "claims.confidentialText": "We maintain strict confidentiality and protect your personal information throughout the process.",
    "claims.submitClaim": "Submit an Injury Claim",
    "claims.submitClaimDesc": "Fill out the form below and our team will contact you",
    "claims.name": "Name",
    "claims.contactNumber": "Best Contact Number",
    "claims.address": "Address",
    "claims.accidentDate": "Accident Date",
    "claims.atFault": "Were You At Fault?",
    "claims.select": "Select...",
    "claims.yes": "Yes",
    "claims.no": "No",
    "claims.partial": "Partially",
    "claims.unknown": "Unknown",
    "claims.injuryArea": "Area of Bodily Injury",
    "claims.injuryAreaPlaceholder": "e.g., Lower back, Neck, etc.",
    "claims.photosVideos": "Photos/Videos of Injury or Accident (Optional)",
    "claims.referralSource": "How Did You Hear About Us? (Optional)",
    "claims.referralSourcePlaceholder": "e.g., Friend, Google, Social Media, etc.",
    "claims.submitting": "Submitting...",
    "claims.submitClaimBtn": "Submit Claim",
    "claims.claimSubmitted": "Claim Submitted",
    "claims.claimSubmittedDesc": "We've received your claim information and will contact you soon!",
    "claims.submissionFailed": "Submission Failed",
    "claims.submissionFailedDesc": "There was an error submitting your claim. Please try again.",

    // Auth
    "auth.welcome": "Welcome",
    "auth.signInDesc": "Sign in to manage your account or create a new one",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.fullName": "Full Name",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.resetPassword": "Reset Password",
    "auth.resetPasswordDesc": "Enter your email address and we'll send you a link to reset your password.",
    "auth.sendResetLink": "Send Reset Link",
    "auth.createAccount": "Create Account",
    "auth.error": "Error",
    "auth.success": "Success!",
    "auth.accountCreated": "Account created successfully. You can now log in.",
    "auth.checkEmail": "Check your email",
    "auth.resetLinkSent": "We've sent you a password reset link.",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcomeBack": "Welcome back,",
    "dashboard.signOut": "Sign Out",
    "dashboard.quoteOfDay": "Quote of the Day",
    "dashboard.loadingInspiration": "Loading inspiration...",
    "dashboard.yourBhphAccount": "Your BHPH Account",
    "dashboard.bhphFinancing": "Buy Here Pay Here Financing",
    "dashboard.currentBalance": "Current Balance",
    "dashboard.monthlyPayment": "Monthly Payment",
    "dashboard.nextPaymentDue": "Next Payment Due",
    "dashboard.yourVehicle": "Your Vehicle",
    "dashboard.makePayment": "Make a Payment",
    "dashboard.accountBalance": "Account Balance",
    "dashboard.noActiveAccounts": "No active accounts",
    "dashboard.vehicles": "Vehicles",
    "dashboard.activeVehicles": "Active vehicles",
    "dashboard.payments": "Payments",
    "dashboard.totalPayments": "Total payments",
    "dashboard.userManagement": "User Management",
    "dashboard.userManagementDesc": "Manage user accounts and admin permissions",
    "dashboard.manageUsers": "Manage Users",
    "dashboard.vehicleManagement": "Vehicle Management",
    "dashboard.vehicleManagementDesc": "Manage vehicle inventory",
    "dashboard.manageVehicles": "Manage Vehicles",
    "dashboard.bhphAccountManagement": "BHPH Account Management",
    "dashboard.bhphAccountManagementDesc": "Add accounts, set interest rates, and manage payments",
    "dashboard.addBhphAccount": "Add BHPH Account",
    "dashboard.editAccounts": "Edit Accounts / Interest Rates",
    "dashboard.recordPayments": "Record Payments",
    "dashboard.paymentReports": "Payment Reports",
    "dashboard.claimsPortal": "Claims Portal",
    "dashboard.claimsPortalDesc": "Add new claim users and track claim progress",
    "dashboard.addNewClaimUser": "Add New Claim User",
    "dashboard.trackClaimProgress": "Track Claim Progress",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.recentActivityDesc": "Your recent transactions and updates",
    "dashboard.noRecentActivity": "No recent activity",
  },
  es: {
    // Navbar
    "nav.inventory": "Inventario",
    "nav.carRepairs": "Reparaciones",
    "nav.injuryClaims": "Reclamos",
    "nav.login": "Iniciar Sesión",
    "nav.dashboard": "Panel",
    "nav.getStarted": "Comenzar",
    "nav.tagline": "Autos Extranjeros y Domésticos de Calidad",
    
    // Hero
    "hero.title": "Cars & Claims",
    "hero.subtitle": "Su socio de confianza para ventas de vehículos, financiamiento y reclamos por lesiones y daños a la propiedad sin culpa",
    "hero.viewInventory": "Ver Inventario",
    "hero.injuryClaims": "Reclamos por Lesiones",
    "hero.carRepairs": "Reparaciones de Autos",
    "hero.bhph": "Compre Aquí Pague Aquí",
    
    // Services
    "services.title": "Nuestros Servicios",
    "services.subtitle": "Todo lo que necesitas en un solo lugar",
    "services.autoSales": "Venta de Autos",
    "services.autoSalesDesc": "Vehículos usados extranjeros y domésticos con precios transparentes",
    "services.bhphFinancing": "Financiamiento compre-aquí-pague-aquí",
    "services.digitalReceipts": "Recibos de pago digitales",
    "services.flexiblePayments": "Horarios de pago flexibles",
    "services.carRepairs": "Reparaciones de Autos",
    "services.carRepairsDesc": "Servicios profesionales de reparación y mantenimiento",
    "services.expertMechanics": "Mecánicos expertos",
    "services.fastTurnaround": "Tiempos de entrega rápidos",
    "services.qualityParts": "Piezas y servicio de calidad",
    "services.injuryClaims": "Reclamos por Lesiones",
    "services.injuryClaimsDesc": "Asistencia profesional en reclamos sin culpa",
    "services.expertProcessing": "Procesamiento experto de reclamos",
    "services.docSupport": "Soporte de documentación",
    "services.fastResolution": "Resolución rápida de reclamos",
    
    // CTA
    "cta.title": "¿Listo para comenzar?",
    "cta.subtitle": "Cree una cuenta para administrar sus pagos o explore nuestro inventario",
    "cta.createAccount": "Crear Cuenta",
    
    // Footer
    "footer.contactUs": "Contáctenos",
    
    // Language Toggle
    "lang.english": "EN",
    "lang.spanish": "ES",

    // Inventory
    "inventory.title": "Inventario de Vehículos",
    "inventory.subtitle": "Explore nuestra selección de vehículos extranjeros y domésticos de calidad de Quality Foreign and Domestic Auto's",
    "inventory.noVehicles": "No hay vehículos disponibles en este momento. ¡Vuelva pronto!",
    "inventory.photos": "Fotos",
    "inventory.call": "Llamar",
    "inventory.buyNow": "Comprar",
    "inventory.mi": "mi",
    "inventory.translating": "Traduciendo...",

    // Purchase Application
    "purchase.title": "Solicitud de Compra",
    "purchase.paymentCalculator": "Calculadora de Pagos",
    "purchase.downPayment": "Enganche ($)",
    "purchase.term": "Plazo (meses)",
    "purchase.estMonthly": "Est. Mensual",
    "purchase.amountFinanced": "Monto Financiado",
    "purchase.totalInterest": "Interés Total",
    "purchase.totalPayment": "Pago Total",
    "purchase.disclaimer": "* Pagos estimados basados en {rate}% APR de interés simple. Los términos reales pueden variar.",
    "purchase.yourInfo": "Su Información",
    "purchase.fullName": "Nombre Completo *",
    "purchase.email": "Correo Electrónico *",
    "purchase.phone": "Número de Teléfono *",
    "purchase.address": "Dirección *",
    "purchase.notes": "Notas Adicionales (Opcional)",
    "purchase.notesPlaceholder": "Cualquier información adicional...",
    "purchase.cancel": "Cancelar",
    "purchase.submitting": "Enviando...",
    "purchase.submit": "Enviar Solicitud",
    "purchase.successTitle": "¡Solicitud Enviada!",
    "purchase.successMessage": "Gracias por su interés en el {vehicle}. Nuestro equipo revisará su solicitud y lo contactará pronto.",
    "purchase.estPayment": "Su Pago Estimado",
    "purchase.perMonth": "/mes",
    "purchase.forMonths": "por {months} meses",
    "purchase.continueBrowsing": "Continuar Navegando",
    "purchase.goToPortal": "Ir al Portal de Pagos",

    // ChatBot
    "chat.title": "Asistente de Cars & Claims",
    "chat.placeholder": "Escribe un mensaje...",
    "chat.inventory": "Inventario",
    "chat.claims": "Reclamos",
    "chat.repairs": "Reparaciones",
    "chat.payments": "Pagos",

    // Payment Portal
    "portal.title": "Portal de Pagos BHPH",
    "portal.subtitle": "Administra tu cuenta y realiza pagos",
    "portal.signInDesc": "Inicia sesión para ver tu cuenta, hacer pagos y ver tu historial de pagos.",
    "portal.signIn": "Iniciar Sesión para Continuar",
    "portal.useCalculator": "O usa nuestra calculadora de pagos abajo",
    "portal.loading": "Cargando...",
    "portal.noActiveAccount": "Sin Cuenta Activa",
    "portal.noActiveAccountDesc": "No tienes una cuenta BHPH activa. ¡Visita nuestra concesionaria para comenzar!",
    "portal.viewInventory": "Ver Inventario",
    "portal.overview": "Resumen",
    "portal.history": "Historial",
    "portal.calculator": "Calculadora",
    "portal.currentBalance": "Saldo Actual",
    "portal.monthlyPayment": "Pago Mensual",
    "portal.nextPaymentDue": "Próximo Pago",
    "portal.daysOverdue": "{days} días de atraso",
    "portal.dueInDays": "Vence en {days} días",
    "portal.daysUntilDue": "{days} días para vencer",
    "portal.vehicle": "Vehículo",
    "portal.originalAmount": "Monto Original",
    "portal.paymentInitiated": "¡Pago Iniciado!",
    "portal.paymentProcessing": "Tu pago está siendo procesado. El saldo de tu cuenta se actualizará pronto.",
    "portal.dismiss": "Cerrar",
    "portal.paymentHistory": "Historial de Pagos",
    "portal.viewPastPayments": "Ver todos tus pagos anteriores",
    "portal.noPaymentHistory": "Sin historial de pagos aún",
    "portal.date": "Fecha",
    "portal.amount": "Monto",
    "portal.principal": "Principal",
    "portal.interest": "Interés",
    "portal.lateFee": "Cargo por Atraso",
    "portal.method": "Método",
    "portal.paymentCalculator": "Calculadora de Pagos",
    "portal.calcDesc": "Calcula pagos con interés simple",
    "portal.calcDescAlt": "Calcula tus pagos mensuales con interés simple",
    "portal.vehiclePrice": "Precio del Vehículo ($)",
    "portal.interestRate": "Tasa de Interés (%)",
    "portal.termMonths": "Plazo (meses)",
    "portal.calculatePayment": "Calcular Pago",
    "portal.totalInterest": "Interés Total",
    "portal.totalPayment": "Pago Total",
    "portal.makePayment": "Realizar un Pago",
    "portal.chooseMethod": "Elige tu método de pago preferido",
    "portal.paymentAmount": "Monto del Pago",
    "portal.monthly": "Mensual",
    "portal.currentBalanceLabel": "Saldo actual",
    "portal.creditDebit": "Tarjeta de Crédito/Débito",
    "portal.recommended": "Recomendado",
    "portal.payWithCard": "Pagar {amount} con Tarjeta",
    "portal.processing": "Procesando...",
    "portal.cashApp": "Cash App",
    "portal.zelle": "Zelle",
    "portal.includeNameNote": "Incluye tu nombre en la nota del pago para un procesamiento más rápido",
    "portal.sendToZelle": "Envía a {contact} e incluye tu nombre en el memo",
    "portal.paymentQuestions": "¿Preguntas sobre pagos? Llámanos al",

    // Repairs
    "repairs.title": "Servicios de Reparación de Autos",
    "repairs.subtitle": "Reparación y mantenimiento profesional de autos de Quality Foreign and Domestic Auto's",
    "repairs.expertMechanics": "Mecánicos Expertos",
    "repairs.expertMechanicsDesc": "Técnicos certificados con años de experiencia",
    "repairs.expertMechanicsText": "Nuestros mecánicos calificados están capacitados para trabajar en vehículos extranjeros y domésticos, garantizando reparaciones de calidad cada vez.",
    "repairs.fastService": "Servicio Rápido",
    "repairs.fastServiceDesc": "Tiempos de entrega rápidos sin comprometer la calidad",
    "repairs.fastServiceText": "Entendemos que su tiempo es valioso. La mayoría de las reparaciones se completan en 24-48 horas.",
    "repairs.completeService": "Servicio Completo",
    "repairs.completeServiceDesc": "Desde cambios de aceite hasta reparaciones mayores",
    "repairs.completeServiceText": "Manejamos todo, desde mantenimiento de rutina hasta reparaciones y diagnósticos complejos del motor.",
    "repairs.qualityParts": "Piezas de Calidad",
    "repairs.qualityPartsDesc": "Piezas OEM y de alta calidad del mercado secundario",
    "repairs.qualityPartsText": "Usamos solo las mejores piezas para garantizar que su vehículo funcione sin problemas y de manera segura.",
    "repairs.servicesInclude": "Nuestros Servicios Incluyen",
    "repairs.servicesIncludeDesc": "Reparación y mantenimiento automotriz integral",
    "repairs.engineDiagnostics": "Diagnóstico y Reparación del Motor",
    "repairs.engineDiagnosticsDesc": "Servicios completos del motor y solución de problemas",
    "repairs.brakeServices": "Servicios de Frenos",
    "repairs.brakeServicesDesc": "Pastillas de freno, rotores y reparación completa del sistema de frenos",
    "repairs.transmissionService": "Servicio de Transmisión",
    "repairs.transmissionServiceDesc": "Reparación y mantenimiento de transmisión",
    "repairs.oilChanges": "Cambios de Aceite y Afinaciones",
    "repairs.oilChangesDesc": "Mantenimiento regular para mantener su auto funcionando sin problemas",
    "repairs.suspension": "Suspensión y Dirección",
    "repairs.suspensionDesc": "Alineación, amortiguadores y reparaciones del sistema de dirección",
    "repairs.electrical": "Sistemas Eléctricos",
    "repairs.electricalDesc": "Batería, alternador y diagnósticos eléctricos",
    "repairs.acHeating": "Aire Acondicionado y Calefacción",
    "repairs.acHeatingDesc": "Reparación y mantenimiento del sistema de climatización",
    "repairs.tireServices": "Servicios de Llantas",
    "repairs.tireServicesDesc": "Rotación, balanceo y reemplazo de llantas",
    "repairs.requestQuote": "Solicitar Cotización de Reparación",
    "repairs.requestQuoteDesc": "Complete el formulario a continuación y nos comunicaremos con usted pronto",
    "repairs.name": "Nombre",
    "repairs.phone": "Número de Teléfono",
    "repairs.address": "Dirección",
    "repairs.year": "Año",
    "repairs.make": "Marca",
    "repairs.model": "Modelo",
    "repairs.issueDescription": "Descripción del Problema",
    "repairs.issueDescriptionPlaceholder": "Por favor describa el problema que está experimentando con su vehículo...",
    "repairs.photosVideos": "Fotos/Videos del Problema (Opcional)",
    "repairs.submitting": "Enviando...",
    "repairs.submitInquiry": "Enviar Consulta",
    "repairs.inquirySubmitted": "Consulta Enviada",
    "repairs.inquirySubmittedDesc": "¡Hemos recibido su consulta de reparación y nos comunicaremos con usted pronto!",
    "repairs.submissionFailed": "Error al Enviar",
    "repairs.submissionFailedDesc": "Hubo un error al enviar su consulta. Por favor intente de nuevo.",

    // Claims
    "claims.title": "Reclamos por Lesiones Sin Culpa",
    "claims.subtitle": "Asistencia profesional para sus necesidades de reclamos por lesiones",
    "claims.expertGuidance": "Orientación Experta",
    "claims.expertGuidanceDesc": "Navegue el proceso de reclamos con apoyo profesional",
    "claims.expertGuidanceText": "Nuestro equipo experimentado le ayuda a entender sus derechos y navegar el proceso de reclamos sin culpa de manera eficiente.",
    "claims.docSupport": "Soporte de Documentación",
    "claims.docSupportDesc": "Ayuda con todo el papeleo y documentación requerida",
    "claims.docSupportText": "Le asistimos con la recopilación y organización de toda la documentación necesaria para respaldar su reclamo.",
    "claims.fastProcessing": "Procesamiento Rápido",
    "claims.fastProcessingDesc": "Respuesta rápida en envíos de reclamos",
    "claims.fastProcessingText": "Trabajamos eficientemente para asegurar que su reclamo sea procesado lo más rápido posible.",
    "claims.confidential": "Servicio Confidencial",
    "claims.confidentialDesc": "Su información está protegida y segura",
    "claims.confidentialText": "Mantenemos estricta confidencialidad y protegemos su información personal durante todo el proceso.",
    "claims.submitClaim": "Enviar un Reclamo por Lesiones",
    "claims.submitClaimDesc": "Complete el formulario a continuación y nuestro equipo se comunicará con usted",
    "claims.name": "Nombre",
    "claims.contactNumber": "Mejor Número de Contacto",
    "claims.address": "Dirección",
    "claims.accidentDate": "Fecha del Accidente",
    "claims.atFault": "¿Fue Usted el Culpable?",
    "claims.select": "Seleccionar...",
    "claims.yes": "Sí",
    "claims.no": "No",
    "claims.partial": "Parcialmente",
    "claims.unknown": "Desconocido",
    "claims.injuryArea": "Área de Lesión Corporal",
    "claims.injuryAreaPlaceholder": "ej., Espalda baja, Cuello, etc.",
    "claims.photosVideos": "Fotos/Videos de la Lesión o Accidente (Opcional)",
    "claims.referralSource": "¿Cómo Supo de Nosotros? (Opcional)",
    "claims.referralSourcePlaceholder": "ej., Amigo, Google, Redes Sociales, etc.",
    "claims.submitting": "Enviando...",
    "claims.submitClaimBtn": "Enviar Reclamo",
    "claims.claimSubmitted": "Reclamo Enviado",
    "claims.claimSubmittedDesc": "¡Hemos recibido su información de reclamo y nos comunicaremos con usted pronto!",
    "claims.submissionFailed": "Error al Enviar",
    "claims.submissionFailedDesc": "Hubo un error al enviar su reclamo. Por favor intente de nuevo.",

    // Auth
    "auth.welcome": "Bienvenido",
    "auth.signInDesc": "Inicie sesión para administrar su cuenta o cree una nueva",
    "auth.signIn": "Iniciar Sesión",
    "auth.signUp": "Registrarse",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.fullName": "Nombre Completo",
    "auth.rememberMe": "Recordarme",
    "auth.forgotPassword": "¿Olvidó su contraseña?",
    "auth.resetPassword": "Restablecer Contraseña",
    "auth.resetPasswordDesc": "Ingrese su correo electrónico y le enviaremos un enlace para restablecer su contraseña.",
    "auth.sendResetLink": "Enviar Enlace",
    "auth.createAccount": "Crear Cuenta",
    "auth.error": "Error",
    "auth.success": "¡Éxito!",
    "auth.accountCreated": "Cuenta creada exitosamente. Ya puede iniciar sesión.",
    "auth.checkEmail": "Revise su correo",
    "auth.resetLinkSent": "Le hemos enviado un enlace para restablecer su contraseña.",

    // Dashboard
    "dashboard.title": "Panel",
    "dashboard.welcomeBack": "Bienvenido de nuevo,",
    "dashboard.signOut": "Cerrar Sesión",
    "dashboard.quoteOfDay": "Frase del Día",
    "dashboard.loadingInspiration": "Cargando inspiración...",
    "dashboard.yourBhphAccount": "Su Cuenta BHPH",
    "dashboard.bhphFinancing": "Financiamiento Compre Aquí Pague Aquí",
    "dashboard.currentBalance": "Saldo Actual",
    "dashboard.monthlyPayment": "Pago Mensual",
    "dashboard.nextPaymentDue": "Próximo Pago",
    "dashboard.yourVehicle": "Su Vehículo",
    "dashboard.makePayment": "Realizar un Pago",
    "dashboard.accountBalance": "Saldo de Cuenta",
    "dashboard.noActiveAccounts": "Sin cuentas activas",
    "dashboard.vehicles": "Vehículos",
    "dashboard.activeVehicles": "Vehículos activos",
    "dashboard.payments": "Pagos",
    "dashboard.totalPayments": "Total de pagos",
    "dashboard.userManagement": "Gestión de Usuarios",
    "dashboard.userManagementDesc": "Administrar cuentas de usuario y permisos de administrador",
    "dashboard.manageUsers": "Administrar Usuarios",
    "dashboard.vehicleManagement": "Gestión de Vehículos",
    "dashboard.vehicleManagementDesc": "Administrar inventario de vehículos",
    "dashboard.manageVehicles": "Administrar Vehículos",
    "dashboard.bhphAccountManagement": "Gestión de Cuentas BHPH",
    "dashboard.bhphAccountManagementDesc": "Agregar cuentas, establecer tasas de interés y administrar pagos",
    "dashboard.addBhphAccount": "Agregar Cuenta BHPH",
    "dashboard.editAccounts": "Editar Cuentas / Tasas de Interés",
    "dashboard.recordPayments": "Registrar Pagos",
    "dashboard.paymentReports": "Reportes de Pagos",
    "dashboard.claimsPortal": "Portal de Reclamos",
    "dashboard.claimsPortalDesc": "Agregar nuevos usuarios de reclamos y seguir el progreso",
    "dashboard.addNewClaimUser": "Agregar Nuevo Usuario de Reclamo",
    "dashboard.trackClaimProgress": "Seguir Progreso de Reclamos",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.recentActivityDesc": "Sus transacciones y actualizaciones recientes",
    "dashboard.noRecentActivity": "Sin actividad reciente",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
